package com.gymapp.modules.reports.enums;

public enum ReportType {
    DAILY_SUMMARY,
    WEEKLY_SUMMARY,
    MONTHLY_SUMMARY,
    MEMBER_GROWTH,
    REVENUE_SUMMARY,
    ATTENDANCE_SUMMARY,
    TRAINER_PERFORMANCE,
    EQUIPMENT_STATUS,
    SHOP_SALES,
    NUTRITION_ADHERENCE,
    WORKOUT_COMPLIANCE,
    LEAD_CONVERSION
}
